# Generated by Django 4.0.5 on 2022-07-03 04:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('Tc', 'Trachea'), ('Al', 'Anterior left'), ('Ar', 'Anterior right'), ('Pl', 'Posterior left'), ('Pr', 'Posterior right'), ('Ll', 'Lateral left'), ('Lr', 'Lateral right')], max_length=15, verbose_name='body location')),
                ('mode', models.CharField(blank=True, max_length=20, verbose_name='mode')),
                ('comments', models.TextField(blank=True, max_length=255, verbose_name='comments')),
                ('file', models.FileField(blank=True, upload_to='uploads/audio/%Y/%m/%d/', verbose_name='audio file')),
            ],
            options={
                'verbose_name': 'audio',
                'verbose_name_plural': 'audios',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('population', models.PositiveIntegerField(default=0, verbose_name='population')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('population', models.PositiveBigIntegerField(null=True, verbose_name='population')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='MedicalArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'medical area',
                'verbose_name_plural': 'medical areas',
            },
        ),
        migrations.CreateModel(
            name='MedicalInstrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'medical instrument',
                'verbose_name_plural': 'medical instruments',
            },
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestions', models.TextField(blank=True, max_length=255, verbose_name='suggestions')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.doctor', verbose_name='doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.patient', verbose_name='patient')),
            ],
            options={
                'verbose_name': "user's history",
                'verbose_name_plural': "user's histories",
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('address', models.CharField(max_length=255, verbose_name='address')),
                ('phone_number', models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^[0-9]*$', message='only numbers')], verbose_name='phone number')),
                ('legal_id', models.CharField(default='', max_length=10, unique=True, verbose_name='legal id')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.city', verbose_name='city')),
                ('doctors', models.ManyToManyField(to='user.doctor', verbose_name='doctors')),
                ('medical_areas', models.ManyToManyField(to='app.medicalarea', verbose_name='medical areas')),
                ('patients', models.ManyToManyField(to='user.patient', verbose_name='patients')),
            ],
            options={
                'verbose_name': 'hospital',
                'verbose_name_plural': 'hospitals',
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numestdo', models.CharField(choices=[('0', 'Health'), ('1', 'Wheezing'), ('2', 'Crackle'), ('3', 'Twice')], max_length=10, verbose_name='health status')),
                ('interval', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('([0-5]?\\d):[0-5]\\d\\s?-\\s?([0-5]?\\d):[0-5]\\d', message='Write intervals in format: MM:SS - MM:SS')], verbose_name='interval')),
                ('status', models.CharField(choices=[('Normal', 'Normal'), ('Wheeze', 'Wheeze'), ('Crackle', 'Crackle'), ('Twice', 'Wheeze and Crackle')], max_length=18, verbose_name='status')),
                ('variance', models.FloatField(null=True, verbose_name='variance')),
                ('range_cycle', models.FloatField(null=True, verbose_name='range')),
                ('sma_coarse', models.FloatField(null=True, verbose_name='SMA coarse')),
                ('sma_fine', models.FloatField(null=True, verbose_name='SMA fine')),
                ('avg_spectre', models.FloatField(null=True, verbose_name='average spectre')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.audio', verbose_name='audio file')),
            ],
            options={
                'verbose_name': 'cycle',
                'verbose_name_plural': 'cycles',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.country', verbose_name='country'),
        ),
        migrations.AddField(
            model_name='audio',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.city', verbose_name='city'),
        ),
        migrations.AddField(
            model_name='audio',
            name='instrument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.medicalinstrument', verbose_name='instrument'),
        ),
        migrations.AddField(
            model_name='audio',
            name='user_history',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.userhistory', verbose_name='user history'),
        ),
    ]
