# Generated by Django 4.0.5 on 2022-07-08 02:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_location_audio_chest_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='mode',
            field=models.CharField(blank=True, choices=[('sc', 'Sequential/Single channel (sc)'), ('mc', 'Simultaneus/Multi-channel (mc)')], max_length=20, verbose_name='mode'),
        ),
    ]
