# Generated by Django 4.0.5 on 2022-07-08 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_audio_created_at_alter_audio_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=100, verbose_name='diagnosis'),
        ),
    ]
