# Generated by Django 4.0.5 on 2022-07-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_audio_diagnosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='diagnosis',
        ),
        migrations.AddField(
            model_name='audio',
            name='diagnostic',
            field=models.CharField(blank=True, max_length=100, verbose_name='diagnostic'),
        ),
        migrations.AddField(
            model_name='cycle',
            name='diagnostic',
            field=models.CharField(blank=True, max_length=100, verbose_name='diagnostic'),
        ),
    ]
