# Generated by Django 4.0.5 on 2022-07-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_audio_diagnosis_remove_cycle_diagnosis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='diagnostic',
        ),
        migrations.RemoveField(
            model_name='cycle',
            name='diagnostic',
        ),
        migrations.AddField(
            model_name='audio',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=100, verbose_name='diagnosis'),
        ),
        migrations.AddField(
            model_name='cycle',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=100, verbose_name='diagnosis'),
        ),
    ]
