# Generated by Django 4.0.5 on 2022-07-04 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_location_audio_chest_location_and_more'),
        ('user', '0002_remove_patient_attending_doctor_doctor_medical_areas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.AddField(
            model_name='patient',
            name='adult_bmi',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='adult BMI'),
        ),
        migrations.AddField(
            model_name='patient',
            name='child_height',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='child weight'),
        ),
        migrations.AddField(
            model_name='patient',
            name='child_weight',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='child weight'),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.FloatField(null=True, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=128, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.city', verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='photo'),
        ),
    ]
