# Generated by Django 4.0.5 on 2022-07-03 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='attending_doctor',
        ),
        migrations.AddField(
            model_name='doctor',
            name='medical_areas',
            field=models.ManyToManyField(to='app.medicalarea', verbose_name='medical areas'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='role',
            field=models.CharField(default='', max_length=30, verbose_name='role'),
        ),
        migrations.AddField(
            model_name='user',
            name='blood_type',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], default='A', max_length=2, verbose_name='blood type'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.city', verbose_name='city'),
        ),
        migrations.AddField(
            model_name='user',
            name='rh_factor',
            field=models.CharField(choices=[('+', '+'), ('-', '-')], default='+', max_length=1, verbose_name='rh factor'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('I', 'Intersexual'), ('N', 'No response')], max_length=11, verbose_name='sex'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True, verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='user',
            name='legal_id',
            field=models.CharField(max_length=10, verbose_name='legal ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='legal_id_type',
            field=models.CharField(choices=[('TI', 'TI'), ('CC', 'CC'), ('NIT', 'NIT'), ('Pass', 'Passport')], default='CC', max_length=10, verbose_name='ID type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(null=True, upload_to='uploads/', verbose_name='photo'),
        ),
    ]
